from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Frame, PageTemplate, NextPageTemplate
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Line, String, Rect
from reportlab.graphics import renderPDF
import json
import os
from pypdf import PdfWriter

# Theme
THEME_COLOR_PRIMARY = colors.maroon
THEME_COLOR_SECONDARY = colors.gold

class PDFGenerator:
    def __init__(self, filename, data, predictions_path="kundali_app/data/predictions.json"):
        self.filename = filename
        self.data = data
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()
        
        try:
            with open(predictions_path, "r") as f:
                self.pred_db = json.load(f)
        except:
             self.pred_db = {"interpretations": {}, "houses_intro": {}, "planet_nature": {}, "dashas": {}, "transits": {}}

    def _add_custom_styles(self):
        self.styles.add(ParagraphStyle(name='PremiumTitle', fontSize=24, leading=28, alignment=1, textColor=THEME_COLOR_PRIMARY, fontName='Helvetica-Bold'))
        self.styles.add(ParagraphStyle(name='PremiumHeading1', fontSize=18, leading=22, spaceBefore=12, spaceAfter=6, textColor=THEME_COLOR_PRIMARY, fontName='Helvetica-Bold'))
        self.styles.add(ParagraphStyle(name='PremiumBodyText', fontSize=11, leading=14, spaceBefore=6, textColor=colors.black, alignment=4))
        self.styles.add(ParagraphStyle(name='ChartText', fontSize=8, alignment=1, textColor=colors.darkblue))
        if 'Normal' not in self.styles:
            self.styles.add(ParagraphStyle(name='Normal', fontSize=10, leading=12, textColor=colors.black))

    def _draw_cover_page(self, canvas, doc):
        canvas.saveState()
        # Purple Background
        canvas.setFillColor(colors.HexColor('#2c0e37'))
        width, height = A4
        canvas.rect(0, 0, width, height, fill=True, stroke=False)
        
        # Mandala
        asset_dir = os.path.join(os.getcwd(), 'kundali_app/assets')
        mandala_path = os.path.join(asset_dir, 'mandala.png')
        book_path = os.path.join(asset_dir, 'book.png')
        
        if os.path.exists(mandala_path):
            img_w, img_h = 400, 400
            canvas.drawImage(mandala_path, (width-img_w)/2, height-450, width=img_w, height=img_h, mask='auto', preserveAspectRatio=True)
            
        # Title Text
        canvas.setFillColor(colors.white)
        canvas.setFont("Times-Roman", 16)
        canvas.drawCentredString(width/2, height - 250, "YOUR")
        canvas.setFont("Times-Roman", 36)
        canvas.drawCentredString(width/2, height - 290, "FORTUNE")
        canvas.drawCentredString(width/2, height - 330, "REPORT")
        
        # Name Badge
        badge_y = height - 420
        canvas.setFillColor(colors.HexColor('#d4af37')) # Gold
        canvas.roundRect((width-300)/2, badge_y, 300, 50, 10, fill=True, stroke=False)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-BoldOblique", 18)
        canvas.drawCentredString(width/2, badge_y + 18, self.data['birth_details']['name'])

        # Book Image
        if os.path.exists(book_path):
             canvas.drawImage(book_path, (width-300)/2, 100, width=300, height=200, mask='auto', preserveAspectRatio=True)
             
        # Borders
        canvas.setStrokeColor(colors.HexColor('#d4af37'))
        canvas.setLineWidth(2)
        canvas.line(20, height-20, 20, height-100)
        canvas.line(20, height-20, 100, height-20)
        canvas.line(width-20, height-20, width-20, height-100)
        canvas.line(width-20, height-20, width-100, height-20)
        
        canvas.restoreState()

    def _border_background(self, canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(THEME_COLOR_PRIMARY)
        canvas.setLineWidth(3)
        canvas.rect(20, 20, A4[0]-40, A4[1]-40)
        canvas.setStrokeColor(THEME_COLOR_SECONDARY)
        canvas.setLineWidth(1)
        canvas.rect(24, 24, A4[0]-48, A4[1]-48)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(A4[0]/2, 10, "Generated by Kundali AI")
        canvas.restoreState()
    
    def _create_chart_drawing(self, planets, title):
        d = Drawing(400, 350)
        size = 250
        x_off, y_off = 75, 25
        
        d.add(String(x_off + size/2, y_off + size + 20, title, textAnchor="middle", fontSize=14, fillColor=THEME_COLOR_PRIMARY, fontName="Helvetica-Bold"))
        d.add(Rect(x_off, y_off, size, size, strokeColor=THEME_COLOR_PRIMARY, strokeWidth=2, fillColor=None))
        d.add(Line(x_off, y_off, x_off+size, y_off+size, strokeColor=THEME_COLOR_PRIMARY))
        d.add(Line(x_off, y_off+size, x_off+size, y_off, strokeColor=THEME_COLOR_PRIMARY))
        
        mid_x, mid_y = x_off + size/2, y_off + size/2
        d.add(Line(x_off, mid_y, mid_x, y_off+size, strokeColor=THEME_COLOR_PRIMARY))
        d.add(Line(mid_x, y_off+size, x_off+size, mid_y, strokeColor=THEME_COLOR_PRIMARY))
        d.add(Line(x_off+size, mid_y, mid_x, y_off, strokeColor=THEME_COLOR_PRIMARY))
        d.add(Line(mid_x, y_off, x_off, mid_y, strokeColor=THEME_COLOR_PRIMARY))
        
        # Simple House Logic
        house_coords = {
            1: (mid_x, y_off + size*0.75), 2: (x_off + size*0.35, y_off + size*0.9),
            3: (x_off + size*0.1, y_off + size*0.65), 4: (x_off + size*0.25, y_off + size*0.5),
            5: (x_off + size*0.1, y_off + size*0.35), 6: (x_off + size*0.35, y_off + size*0.1),
            7: (mid_x, y_off + size*0.2), 8: (x_off + size*0.65, y_off + size*0.1),
            9: (x_off + size*0.9, y_off + size*0.35), 10: (x_off + size*0.75, y_off + size*0.5),
            11: (x_off + size*0.9, y_off + size*0.65), 12: (x_off + size*0.65, y_off + size*0.9)
        }
        
        house_planets = {i: [] for i in range(1, 13)}
        if planets:
            for p in planets:
                h = p.get('house')
                if h: house_planets[h].append(p['planet'][:2])
        
        for h, plist in house_planets.items():
            if not plist or h not in house_coords: continue
            x, y = house_coords[h]
            d.add(String(x, y, " ".join(plist), textAnchor="middle", fontSize=8, fillColor=colors.darkblue))
            
        return d

    def generate(self):
        # 1. Generate Cover
        cover_file = "temp_cover_gen.pdf"
        c = canvas.Canvas(cover_file, pagesize=A4)
        self._draw_cover_page(c, None)
        c.showPage()
        c.save()
        
        # 2. Generate Body
        body_file = "temp_body_gen.pdf"
        doc = SimpleDocTemplate(body_file, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
        frame = Frame(30, 30, A4[0]-60, A4[1]-60, id='normal', leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)
        doc.addPageTemplates([PageTemplate(id='Normal', frames=[frame], onPage=self._border_background)])
        
        story = []
        # Header
        story.append(Paragraph("Astrological Particulars", self.styles['PremiumTitle']))
        story.append(Paragraph("Avakhada Chakra", self.styles['PremiumHeading1']))
        
        # Avakhada Table
        av = self.data.get('avakhada', {})
        av_data = [
            ['Varna', av.get('Varna', '-'), 'Gana', av.get('Gana', '-')],
            ['Yoni', av.get('Yoni', '-'), 'Nadi', av.get('Nadi', '-')],
            ['Sign', av.get('Sign', '-'), 'Nakshatra', av.get('Nakshatra', '-')]
        ]
        t = Table(av_data, colWidths=[1.5*inch, 2*inch, 1.5*inch, 2*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), THEME_COLOR_SECONDARY),
            ('BACKGROUND', (2,0), (2,-1), THEME_COLOR_SECONDARY),
            ('TEXTCOLOR', (0,0), (0,-1), colors.white),
            ('TEXTCOLOR', (2,0), (2,-1), colors.white),
            ('GRID', (0,0), (-1,-1), 1, colors.grey),
            ('ALIGN', (0,0), (-1,-1), 'CENTER')
        ]))
        story.append(t)
        story.append(Spacer(1, 0.3*inch))
        
        # Planetary Table
        story.append(Paragraph("Planetary Positions", self.styles['PremiumHeading1']))
        p_data = [['Planet', 'Sign', 'Degree', 'House', 'Nakshatra', 'Pada']]
        for p in self.data['planets']:
            p_data.append([p['planet'], p['sign'], p['degree'], str(p.get('house', '-')), p.get('nakshatra', '-'), p.get('pada', '-')])
        
        tp = Table(p_data, colWidths=[1.2*inch, 1.2*inch, 1.2*inch, 0.8*inch, 1.5*inch, 0.6*inch])
        tp.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), THEME_COLOR_SECONDARY),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('GRID', (0,0), (-1,-1), 1, colors.grey)
        ]))
        story.append(tp)
        story.append(PageBreak())
        
        # Charts
        story.append(Paragraph("Divisional Charts", self.styles['PremiumHeading1']))
        story.append(self._create_chart_drawing(self.data['planets'], "Lagna Chart (D1)"))
        story.append(Spacer(1, 0.2*inch))
        if 'navamsha' in self.data:
            story.append(self._create_chart_drawing(self.data['navamsha'], "Navamsha (D9)"))
        story.append(PageBreak())
        
        # Predictions
        story.append(Paragraph("Detailed Interpretations", self.styles['PremiumHeading1']))
        for p in self.data['planets']:
            if p['planet'] == "Ascendant": continue
            key = f"{p['planet']}_{p.get('house', '?')}"
            text = self.pred_db['interpretations'].get(key, "General prediction.")
            story.append(Paragraph(f"{p['planet']} in House {p.get('house')}", self.styles['PremiumHeading1']))
            story.append(Paragraph(text, self.styles['PremiumBodyText']))
            story.append(Spacer(1, 0.1*inch))
        story.append(PageBreak())
        
        # Forecasts
        story.append(Paragraph("Monthly Forecasts (2 Years)", self.styles['PremiumHeading1']))
        months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        current_year = 2024
        for y in range(2):
            story.append(Paragraph(f"Year {current_year + y}", self.styles['PremiumHeading1']))
            for m in months:
                story.append(Paragraph(f"<b>{m}</b>: Favorable period for growth.", self.styles['PremiumBodyText']))
                story.append(Spacer(1, 0.05*inch))
            story.append(PageBreak())

        doc.build(story)
        
        # 3. Merge
        merger = PdfWriter()
        merger.append(cover_file)
        merger.append(body_file)
        merger.write(self.filename)
        merger.close()
        
        # Cleanup
        os.remove(cover_file)
        os.remove(body_file)
